# Generated by Django 3.0.5 on 2021-01-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_bonus_character_class_feat_journal_journalpost_race_spell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalPost',
        ),
    ]
