# Generated by Django 3.0.5 on 2021-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_journalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
