# Generated by Django 3.0.5 on 2021-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20210103_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('CON', 'CON'), ('INT', 'INT'), ('WIS', 'WIS'), ('CHA', 'CHA'), ('ANY', 'ANY')], max_length=10),
        ),
    ]
