# Generated by Django 3.0.5 on 2021-01-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20210103_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(null=True, related_name='character_feats', to='forum.Feat'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(null=True, related_name='character_spells', to='forum.Class'),
        ),
    ]
