# Generated by Django 3.0.5 on 2021-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20210111_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='spell',
            field=models.BooleanField(default=False),
        ),
    ]
