# Generated by Django 3.0.5 on 2021-01-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_class_spell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='spell',
            new_name='spellcasting',
        ),
    ]
