# Generated by Django 3.0.5 on 2021-01-11 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0020_auto_20210111_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='user_access',
            field=models.ManyToManyField(blank=True, related_name='journal_acc', to=settings.AUTH_USER_MODEL),
        ),
    ]
