# Generated by Django 3.0.5 on 2021-01-12 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20210111_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, null=True, related_name='character_spells', to='forum.Spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='starting_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Class'),
        ),
    ]
