# Generated by Django 3.0.5 on 2021-01-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20210112_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='character_feats', to='forum.Feat'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default='Human', on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Race'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='character_spells', to='forum.Spell'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='bonuses',
            field=models.ManyToManyField(blank=True, related_name='feat_bonuses', to='forum.Bonus'),
        ),
    ]
